### ISSUE TITLE
Got error when adding new client in omv GUI 

### ISSUE THREAD

**Issue by 2lach** [OpenMediaVault-Plugin-Developers/openmediavault-wireguard#10]
Hey hope all is well!

_Brief summary:_
Tried to add new wg-client with omv gui (my 4th client, all others have worked without issues), when applying the "Pending configuration changes. You must apply these changes in order for them to take effect." i omv i got errors, wg-client was created but not working.

**The longer story:**
I been using the openmediavault-wireguard for some time and it's worked like a charm 😄 

Today i tried adding a new wg-client in my omv userinterface (my 4th client)

and then i got this error:
[omv-wg-error1.txt](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-wireguard/files/9814846/wg-error1.txt)

So i debugged a bit:
```bash
dpkg -l | grep -E "wireguard|openme"
output:
......
openmediavault-wireguard       6.0.1                       all          openmediavault WireGuard plugin
wireguard                                    1.0.20210223-1    all          fast, modern, secure kernel VPN tunnel (metapackage)
wireguard-tools                          1.0.20210223-1    amd64        fast, modern, secure kernel VPN tunnel (userland utilities)

ls -al /usr/bin/wg
output:                                                                                                                                             
.rwxr-xr-x 97k root 25 Feb  2021 /usr/bin/wg

```
I did a system reboot and restarted all wg services
tried to make the wg-client again. but no go

Then i tried installing the pip packages (errors from the wg-error1.txt) but found no my pip3 instance was broken
So that might be it i though.

I re-installed pip3 and tried to install the missing packages and then i get: r 
```BASH
❯ pip3 uninstall urllib3                                                                                  

Found existing installation: urllib3 1.26.5
Uninstalling urllib3-1.26.5:
```
which is the correct version.

tried adding new wg-client from omv gui:
and got second error:
[omv-wg-error-2.txt](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-wireguard/files/9814847/wg-error-2.txt)

It's pretty much the same error as the first one.

I checked the omv forum, stackoverflow and whatnots but didn't find any obvious or similar reasons for the error and i am kinda at a loss here.

If you got a clue what the issue might be it would be awesome

**Comment by ryecoaaron** [comment]
Not having the os python module is going to break a lot of things.  You should not be using pip for any of the python packages.  not much the plugin can do to fix this.

**Comment by 2lach** [comment]
Hey, thanks for your response 👍 I could easily install python at a os level but i don't think that is the real issue.
If you looked in the error log file the issue is when openmediavault runs
`omv-salt deploy run --no-color wireguard 2>&1`  it exits on 1
After i used the plugin from the omv gui, but since the wg-plugin worked two weeks ago something must have changed
Its in regards to this iam looking for advise.
Should i try the reinstall the plugin or might it be an OS update i should revert or review?

**Comment by ryecoaaron** [comment]
I think you are misunderstanding what I am saying.  The python "os" module is missing and that is why wireguard saltstack code is exiting with exit code of 1.  This needs to be fixed on your system.  Since I have no idea what you have installed nor what you have done with pip, I can't tell you what to fix.  I will say that you should not be using pip at all.  There is a very good chance you will install an incompatible version of a python module using pip.

Since this is not something the plugin can fix, I am going to close this issue.  Please open a thread on the forum where more people can see the problem and try to help.

**Comment by 2lach** [comment]
Alrite thanks for your input
Have a nice day
