### ISSUE TITLE
Address other than OMV cannot be accessed

### ISSUE THREAD

**Issue by dongqiceo** [OpenMediaVault-Plugin-Developers/openmediavault-wireguard#13]
![image](https://user-images.githubusercontent.com/12833625/206836433-87c3f563-e6f6-4402-b61b-3067489b4f82.png)
only open 10.192.1.254

**Comment by dongqiceo** [comment]
![image](https://user-images.githubusercontent.com/12833625/206836604-dc26319c-8fe8-4532-8900-59adb4e52921.png)

**Comment by dongqiceo** [comment]
I want to relay other peers via OMV，Currently, only intranet addresses can be used，wg0 address not work

**Comment by dongqiceo** [comment]
![image](https://user-images.githubusercontent.com/12833625/206851941-cc58b294-ef0b-4ebb-8efb-618ac1937f1a.png)
problem is this,but only one peer can set /24,I dont how to fix this bug

**Comment by ryecoaaron** [comment]
This isn't a bug.  It is a design decision.  I don't use wireguard myself or even know what you are trying to do.  But I thought that was the point of the Restrict checkbox in the client config?  Maybe it would help to read through https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-wireguard/pull/7 and https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-wireguard/issues/11

**Comment by dongqiceo** [comment]
> 

ok，I think is my setting error

**Comment by dongqiceo** [comment]
When connecting two peers through a trunk, both AllowedIPs need to set the virtual address of the other
