### ISSUE TITLE
Update tunnels config via shell/programmatically

### ISSUE THREAD

**Issue by Elyg** [OpenMediaVault-Plugin-Developers/openmediavault-wireguard#14]
Hello,

I would like to know if it's possible to update the wireguard tunnels via shell/environment viariable/programatically. Basically, I have setup my wireguard tunnel to access omv, however because of my ISP the public IP changes every few weeks which makes it that I need to update the ip manually

What I was thinking is to run a python script cron job to update the ip when a change is detected. But I am not entirely sure how to push those changes to the omv config/wireguard plugin ?

If it's not possible as it is currently, would it be possible to ask this as a feature request either be able to update it via shell or have the omv wireguard plug use an environment variable that I could then update from my cron job

Thanks

**Comment by ryecoaaron** [comment]
You would just need code that could update the entry in the OMV database (/etc/openmediavault/config.xml) and the execute sudo omv-salt deploy run wireguard.

**Comment by xhente** [comment]
> What I was thinking is to run a python script cron job to update the ip when a change is detected. But I am not entirely sure how to push those changes to the omv config/wireguard plugin ?

To solve the dynamic IP the best solution is to point to a domain instead of a public IP. The plugin supports domains.
You can get a free domain at duckdns for example. Then you just have to set up a cron job that runs the file indicating duckdns to update the IP if it has changed. There are also containers to do this.
This way you no longer have to update anything manually.

**Comment by Elyg** [comment]
> > What I was thinking is to run a python script cron job to update the ip when a change is detected. But I am not entirely sure how to push those changes to the omv config/wireguard plugin ?
> 
> To solve the dynamic IP the best solution is to point to a domain instead of a public IP. The plugin supports domains. You can get a free domain at duckdns for example. Then you just have to set up a cron job that runs the file indicating duckdns to update the IP if it has changed. There are also containers to do this. This way you no longer have to update anything manually.

Ohhh, I didn't even think about this. It's so simple.
I already had a container that was updating my ip for cloudflare dns, so I just added a non proxied domain and used that for the endpoint and it works perfectly

Thank you!
