### ISSUE TITLE
How to backup, restore and retain old keys to a new system

### ISSUE THREAD

**Issue by ilham-Hamzah** [OpenMediaVault-Plugin-Developers/openmediavault-wireguard#15]
Hi,

I'm upgrading hardware and would like to backup existing keys if possible since changing to new keys will be a bit of hassle to deal with.
Kindly advice.

**Comment by ryecoaaron** [comment]
You could copy the wireguard section in the database (/etc/openmediavault/config.xml), install the plugin on the new hardware, then replace the wireguard section in the new database with what you copied.  After that, run:  sudo omv-salt deploy run wireguard

**Comment by ilham-Hamzah** [comment]
Thanks, it's working although some warnings do popup and I need to enable the tunnel first before re-deploy again so the clients show up
