### ISSUE TITLE
Consider adding MTU = 1420 to tunnel

### ISSUE THREAD

**Issue by markusdd** [OpenMediaVault-Plugin-Developers/openmediavault-wireguard#16]
Hi, first of all thanks for this amazing plugin!

Nevertheless I was chasing down a very weird issue for the past 2 weeks.
Usually I use PiVPN, but as at my parents house I deployed a small OMV NAS, I felt I could use just OMVs plugin to establish the wireguard endpoint.

Connections themselves immidiately worked, and traffic was runing smoothly for my windoows and Android endpoints.

The only issue I had was my Macbook Pro (M1 Pro, MacOS Ventura, latest greatest). The tunnel would establish, but no traffic was going through. Routes looked fine. Changing AllowedIPs did not change anything.
Using one of my other endpoints where the Pi-VPN setup is running, I did not have this problem. Also the still existing older IPSec endpoints were working fine as well.

As the client setups (except for keys obviously) were identical, I compared the server configs between OMV and PiVPN, turns out PiVPN has an MTU =1420 setting, which it inserted per default (I did not specify that in the wizard).

I then added this to the OMV plugin config via the terminal, and see: It immdiately works, also with the MacBook.

It seems like the default MTU for Wireguard is 1500, which usually will always be less then ideal, because most ISPs use VLANs which reduces MTU, local VPNs are adapters than can reduce MTU and if you are on a cellular hotspot the MTU is also smaller. So in the best case all you get is fragmentation, in this very case it really seems to hinder the proper establishment of the connection on MacOS.

After scanning reddit and the oofficial Wireguard IRC, it seems this issue is more common than I thought.

That is why I hereby would propose to make an MTU setting of 1420 the default. It is a sane value I also know from other VPN types and technically it makes sense, as 1500 will almost never work properly without fragments. This should also help many Mac users who face this hard to debug problem and should increase performance for others.

**Comment by Dabsunter** [comment]
It might also be a good idea to make it configurable per Tunnel. Indeed 1420 is a common value I encountered without issues but I have to say I neither encountered any issues with this value unset 🤷‍♂️

**Comment by xhente** [comment]
There is a new version of the plugin that fixes this problem. You can refer to the omv-extras wiki on how to customize the MTU value. https://wiki.omv-extras.org/doku.php?id=omv6:omv6_plugins:wireguard#configuring_a_tunnel 

@markusdd 
In your case you probably need a value less than 1420. The `ip addr` command will tell you the MTU value that your tunnel currently has configured.
