### ISSUE TITLE
Error code when deleting Custom Config

### ISSUE THREAD

**Issue by RMNB** [OpenMediaVault-Plugin-Developers/openmediavault-wireguard#17]
I added a Custom Config, which works, but it can't be delete. If there is more than one Custom Config, then I can delete configs as long as as its not the last remaining Custom Config. To delete, I disable the custom config and apply the change, then delete the config and apply the change. The error popup header is "500 - Internal Server Error".

**Comment by ryecoaaron** [comment]
I can't replicate that.  Can you cut&paste the full output of the error from the bell in the top right of the OMV interface?

**Comment by RMNB** [comment]
Attaching below:

`Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; omv-salt deploy run --no-color wireguard 2>&1' with exit code '1': debian:

Summary for debian
-----------
Succeeded: 0
Failed:   0
-----------
Total states run:    0
Total run time:  0.000 ms

OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; omv-salt deploy run --no-color wireguard 2>&1' with exit code '1': debian:

Summary for debian
-----------
Succeeded: 0
Failed:   0
-----------
Total states run:    0
Total run time:  0.000 ms in /usr/share/php/openmediavault/system/process.inc:220
Stack trace:
#0 /usr/share/php/openmediavault/engine/module/serviceabstract.inc(62): OMV\System\Process->execute()
#1 /usr/share/openmediavault/engined/rpc/config.inc(174): OMV\Engine\Module\ServiceAbstract->deploy()
#2 [internal function]: Engined\Rpc\Config->applyChanges(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(149): OMV\Rpc\ServiceAbstract->callMethod('applyChanges', Array, Array)
#5 /usr/share/php/openmediavault/rpc/serviceabstract.inc(619): OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}('/tmp/bgstatusZO...', '/tmp/bgoutputWK...')
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(159): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#7 /usr/share/openmediavault/engined/rpc/config.inc(195): OMV\Rpc\ServiceAbstract->callMethodBg('applyChanges', Array, Array)
#8 [internal function]: Engined\Rpc\Config->applyChangesBg(Array, Array)
#9 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#10 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('applyChangesBg', Array, Array)
#11 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Config', 'applyChangesBg', Array, Array, 1)
#12 {main}`

**Comment by ryecoaaron** [comment]
Can you post the output of:

sudo omv-showkey wireguard
sudo omv-salt deploy run wireguard

**Comment by ryecoaaron** [comment]
Fix in 6.3.4 in the repo now.
