### ISSUE TITLE
OMV not responding after setting tunnel interface IP to host IP

### ISSUE THREAD

**Issue by M4X1K02** [OpenMediaVault-Plugin-Developers/openmediavault-wireguard#18]
I have the latest version of OMV installed on my RaspeberryPi 4B and it was working for 2 years now.
Recently, I added the Wireguard extension. The extension was not impeding OMV until I (accidentally?) changed the interface IP address of the tunnel to be the same as that of my RaspberryPi.
After hitting 'apply changes' in the OMV web-interface, **OMV stopped responding to any web-requests** (ssh as well).
All ports are closed, this is the only thing I could get from an nmap scan:
```
PORT      STATE         SERVICE
22/udp    open|filtered ssh
51820/udp open|filtered unknown
MAC Address: E4:5F:01:81:4D:E5 (Raspberry Pi Trading)
Too many fingerprints match this host to give specific OS details
Network Distance: 1 hop
```
Neither SSH nor Wireguard is working.
Obviously, I can not use my NAS now at all.
I believe the RaspberryPi is still booting, because the activity LED is blinking and the hard drive attached is spinning.
As I don't have a mini HDMI adapter, I cannot get any more info from my system as of now.

If someone had this issue and solved it somehow I'd appreciate your help.

**Comment by ryecoaaron** [comment]
If you can't access ssh or the web interface, the only way to fix is to login locally requiring the mini hdmi adapter.  After that you could uninstall the wireguard plugin and reboot.

**Comment by M4X1K02** [comment]
After connecting the mini HDMI i was able to purge the extension using
`apt-get --purge remove openmediavault-wireguard`.
The NAS is working again
