### ISSUE TITLE
Server Error when creating a client

### ISSUE THREAD

**Issue by IamSLyToo** [OpenMediaVault-Plugin-Developers/openmediavault-wireguard#22]
Creating a Client from the Web GUI results in a Server Error.
Running Wireguard in OMV7.0

Error message says: 
Line 302 of usr/share/openmediavault/engined/rpc/wireguard.inc: Argument 3 of substr() should be an int.

I could make it work by modifying the line 302 this way:
-    if ((strlen($dnsv) < 7) || (substr(0, 3, $dnsv) == 127)) {
+   if ((strlen($dnsv) < 7) || (substr($dnsv,0,3) == '127')) {

No idea if this is fundamentally correct but at least it solved the error...
Cheers.

**Comment by ryecoaaron** [comment]
You are correct.  Not sure how I messed that one up.  Thanks.  Fixed and new version will be in the repo shortly.
