### ISSUE TITLE
Setting the DNS to 127.0.0.53 setting does not persist and keeps switching back to `disabled`

### ISSUE THREAD

**Issue by trajano** [OpenMediaVault-Plugin-Developers/openmediavault-wireguard#23]
Setting the DNS to 127.0.0.53 setting does not persist and keeps switching back to `disabled`.

As an aside I am actually unable to get this to work so far.  The WireGuard logs show it's connected but it's not resolving anything whether I use IP address or DNS name

**Comment by ryecoaaron** [comment]
The plugin is removing and dns entry starting with 127 - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-wireguard/blob/master/usr/share/openmediavault/engined/rpc/wireguard.inc#L302

I could be wrong but isn't setting a localhost setting being redundant?

**Comment by trajano** [comment]
it may be best to have the drop down say `use local DNS` rather than giving the option of `disabled` / `127.0.0.53` or `custom with 127.0.0.53`

**Comment by ryecoaaron** [comment]
This should be fixed now.
