### ISSUE TITLE
Configuring a Tunnel does not describe the `Local Server` option

### ISSUE THREAD

**Issue by trajano** [OpenMediaVault-Plugin-Developers/openmediavault-wireguard#24]
https://wiki.omv-extras.org/doku.php?id=omv6:omv6_plugins:wireguard#configuring_a_tunnel doesn't include an entry what the `local server` option is used for.

**Comment by ryecoaaron** [comment]
​Looking at the code, if the Local IP checkbox on the client form is checked, the entry from the Local Server field on the tunnel form is appended to the AllowedIPs in the client config.

**Comment by ryecoaaron** [comment]
This should be fixed now.
