### ISSUE TITLE
add  PersistentKeepalive 

### ISSUE THREAD

**Issue by dongqiceo** [OpenMediaVault-Plugin-Developers/openmediavault-wireguard#8]
sorry, my network can't push this little change,somebody do this, just at [peer] config add PersistentKeepalive

**Comment by dongqiceo** [comment]
but this config should be fix in page

**Comment by ryecoaaron** [comment]
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-wireguard/commit/bdb170864e40ce27ae917d8be5730fde406e1367

**Comment by ryecoaaron** [comment]
Should released in the next couple of days.
